### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by mshibuya** [wrike/codeclimate-dart#3]
I'm not sure if this is the right place to ask, but my guess is that @sinegovsky-ivan is the maintainer for [Code Climate Dart plugin](https://docs.codeclimate.com/docs/dart-code-metrics). Sorry if that's not the case.

We're using Code Climate with our Dart project. It worked fine initially, but recently we started experiencing the error like this in the Code Climate analysis:

```
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      getComponentHumanReadableName (package:dart_code_metrics/src/utils/metrics_analyzer_utils.dart:28)
#1      MetricsAnalysisRecorder._endRecordFile.<anonymous closure> (package:dart_code_metrics/src/metrics_analysis_recorder.dart:109)
#2      MapMixin.map (dart:collection/maps.dart:170)
#3      MetricsAnalysisRecorder._endRecordFile (package:dart_code_metrics/src/metrics_analysis_recorder.dart:108)
#4      MetricsAnalysisRecorder.recordFile (package:dart_code_metrics/src/metrics_analysis_recorder.dart:42)
#5      MetricsAnalyzer.runAnalysis (package:dart_code_metrics/src/metrics_analyzer.dart:108)
#6      MetricsAnalysisRunner.run (package:dart_code_metrics/src/metrics_analysis_runner.dart:23)
#7      _runAnalysis (file:///app/bin/metrics.dart:86)
#8      main (file:///app/bin/metrics.dart:24)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)
```

This is not explicitly mentioned but by looking at the stack trace it seems that it's using very old version of [dart_code_metrics](https://github.com/dart-code-checker/dart-code-metrics) (maybe 2.3.x?).
Newer version of dart_code_metrics doesn't seem to have this issue so I want to upgrade it, but I want the build to be run in Code Climate's hosted runner, not locally. To achieve this, upgrading [the official docker image](https://hub.docker.com/r/codeclimate/codeclimate-dart) will be the only solution.

Hence this request. Thank you for your effort of creating and maintaining this project!

**Comment by sinegovsky-ivan** [comment]
Hi! We have updated the project. Please try new version.
